spring.application.name=pizzaCrm
# spring.config.import=optional:file:.env
# spring.datasource.url=${database.url}
# spring.datasource.username=${database.user}
# spring.datasource.password=${database.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
springdoc.api-docs.path=/api-docs

# pass to .env when completed (BUG OF NOT FOUNDING .ENV VARIABLES)
spring.datasource.url=jdbc:mysql://localhost:3306/pizza
spring.datasource.username=testuser
spring.datasource.password=password


jwt.secret=6aKWUIfqYFV/CVInmnWDHlBiHkWR7CXrZwpm464bJBY7p1tERHwh1ECEeILD0bKsjN
jwt.refresh.expiration=900
jwt.access.expiration=3600000

